apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: dacn-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: tuilaphu.id.vn
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: dacn-backend
spec:
  ingressClassName: nginx
  rules:
    - host: api.tuilaphu.id.vn
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80