name: "Terraform"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
permissions: read-all
jobs:
  terraform:
    name: "Terraform"
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY }}
      PRIVATE_KEY: ${{ secrets.SSH_SECRET_KEY }}

    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}   

      - name: Add Access Key
        run: echo '${{ secrets.AWS_ACCESS_KEY }}' >> "accesskey"  

      - name: Add Secret Key
        run: echo '${{ secrets.AWS_SECRET_KEY }}' >> "secretkey"    

      - name: SSH Private key
        run: echo '${{ secrets.SSH_SECRET_KEY }}' >> "ed25519"

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve