name: "Terraform"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
permissions: read-all
jobs:
  terraform:
    name: "Terraform"
    env:
      # AWS secrets
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY }}
      SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}

    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ap-southeast-2   

      - name: SSH Private key
        run: echo '${{ env.SSH_SECRET_KEY }}' >> "ed25519"

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve

      - name: Extract kubeconfig
        id: get_kubeconfig
        run: echo "::set-output name=kubeconfig::$(terraform output -raw kubeconfig)"

      - name: Write kubeconfig to file
        run: echo "${{ steps.get_kubeconfig.outputs.kubeconfig }}" > kubeconfig
  
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.21.2

      - name: Deploy frontend to EKS
        run: kubectl apply -f k8s/frontend-deployment.yml --kubeconfig kubeconfig
    
      - name: Deploy backend to EKS
        run: kubectl apply -f k8s/backend-deployment.yml --kubeconfig kubeconfig